version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: your-mongo-database
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./todo-frontend
    ports:
      - "3000:3000"
    networks:
      - todo-network

  backend:
    build:
      context: ./src
    ports:
      - "8080:8080"
    networks:
      - todo-network

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge
